name: Deploy to AWS Elastic Beanstalk

on:
  # push:
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-west-1

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        eb init -p python-3.12 capstone-test --region us-west-1
        
        ENV_NAME="devops-env"
        TIMEOUT=15

        # Check if the environment exists
        if eb status $ENV_NAME > /dev/null 2>&1; then
            echo "Environment '$ENV_NAME' already exists. Skipping creation."
        else
            echo "Environment '$ENV_NAME' does not exist. Creating it..."
            eb create $ENV_NAME --timeout $TIMEOUT
        fi

        eb deploy